morpho-org/morpho-blue-reward-programs

- README.md
Just adding the FAQ section with the recommended URD
> feat(README): updating the FAQ section of the readme

- src/market-programs.ts
Updating the USDC incentives for cbETH to be directed to the new market: `0x1c21c59df9db44bf6f645d854ee710a8ca17b479451447e9f56758aee10a2fad`
> feat(gauntlet): updated USDC rewards config for cbETH

- src/market-programs.ts
DINERO supply incentives for the apxETH/WETH market on Mainnet
> feat: add dinero incentives markets program

- src/market-programs.ts
Adding PYTH incentives to UNI/USDC Market. 
- 200k PYTH 07/26/2024-09/26/2024 12pm EST
> adding UNI/USDC PYTH incentives

- src/market-programs.ts
Oval OEV from liquidations distributed to Morpho liquidity providers for the wstETH / USDT Morpho market. [Morpho market page](https://risk.morpho.org/market?id=0x6a6c8e41a6a7ccbea68e1e6a19ece1fdd863b2b6c9e0f71bbcd4dcbe8b1062e8).
> feat: Oval OEV rewards wstETH/USDT

- src/market-programs.ts
Oval OEV from liquidations distributed to Morpho liquidity providers for the pufETH/USDC Morpho market. [Morpho market page](https://risk.morpho.org/market?id=0x7e9c708876fa3816c46aeb08937b51aa0461c2af3865ecb306433db8a80b1d1b).
> feat: Oval OEV rewards pufETH/USDC

- src/vault-programs.ts
- Distribute 1.5m WELL tokens starting from thursday to end of current epoch on EURC vault
- Amount is taken from the last epochs that should have been distributed to USDC and WETH vaults
- Distribute 2.5m WELL on EURC vault over the last epoch
- Update the other rewards distrib by subtracting the removed rewards (25m - 5m) / 2 = 10m
> feat: update moonwell rewards with EURC vault

- src/vault-programs.ts
Flagship EURC vault address was incorrect.
> fix(well-incentives): wrong flagship eurc address

- src/market-programs.ts
Add a new market reward program for the cbBTC/USDC market on Mainnet. This program will run from September 26, 2024, to October 3, 2024, at 1pm EST. The reward amount for this program is 10,000 USDC to be split in a 75:25 ratio for the borrow and supply sides respectively.
tx: https://etherscan.io/tx/0x10b605ea4214371ae83bf613e2054cb3365f2c23dcf00f52400c6bb64c2df920
> Add cbBTC/USDC 10K market reward program on Mainnet

- src/market-programs.ts
Oval OEV from liquidations distributed to Morpho liquidity providers for the following markets:
- [wstETH / USDT](https://risk.morpho.org/market?id=0x6a6c8e41a6a7ccbea68e1e6a19ece1fdd863b2b6c9e0f71bbcd4dcbe8b1062e8)
- [pufETH/USDC](https://risk.morpho.org/market?id=0x7e9c708876fa3816c46aeb08937b51aa0461c2af3865ecb306433db8a80b1d1b)
- [tBTC / USDC](https://risk.morpho.org/market?id=0xe4cfbee9af4ad713b41bf79f009ca02b17c001a0c0e7bd2e6a89b1111b3d3f08)
> feat: oval market rewards 240925-241025

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> feat(css):removing useless css code

- src/market-programs.ts
- src/vault-programs.ts
We are incentivizing the newly created [Universal USDC Vault](https://app.morpho.org/vault?vault=0xB7890CEE6CF4792cdCC13489D36D9d42726ab863&network=base) for [Universal Assets](https://app.universalassets.xyz/) and [uSOL/USDC market](https://app.morpho.org/market?id=0xa60e9b888f343351dece4df8251abe5858fc5db96e8624d614a6500c3a3085ea&network=base). 35 uSOL will be distributed as incentives:
- 17.5 uSOL will be distributed towards the Vault.
- 17.5 uSOL will be distributed towards borrowers on the uSOL / USDC market.
> Add uSOL incentives for Universal Vault and uSOL/USDC Market

- src/market-programs.ts
Add 2 new market reward programs for the cbBTC/USDC and wstETH/USDC market on Base. This program will run from October 16, 2024, to October 23, 2024, at 1pm EST. The reward amount for this program is 10,000 USDC for each market to be split in a 75:25 ratio for the borrow and supply sides respectively.
> USDC incentives for cbBTC and wstETH markets $10K from 10/16-10/23

- src/airdrop-programs.ts
This update allow to remove blacklisted AMO: 0x57eedCB68445355e9C11A90F39012e8d4AAA89Fc
> fix: update safe pass repartition

- src/market-programs.ts
Market was misconfigured. 
Formula used was: 
$$new_{rate}=old_{rate}$$
$$new_{amount}/new_{duration}=old_{amount}/old_{duration}$$
$$new_{amount} = old_{amount}*new_{duration}/old_{duration}$$
> fix: PAXG rewards on misconfigured markets

- src/market-programs.ts
Add 2 new market reward programs for the cbBTC/USDC and wstETH/USDC markets on Base. This program will run from October 28, 2024, to November 11, 2024, at 1pm EST. The reward amount for this program is 20,000 USDC for each market to be split in a 75:25 ratio for the borrow and supply sides respectively.
> 20K usdc each to cbbtc-usdc and wsteth-usdc markets on base

- src/market-programs.ts
Fix linting issue on PR: https://github.com/morpho-org/morpho-blue-reward-programs/pull/73
Add 2 new market reward programs for the cbBTC/USDC and wstETH/USDC markets on Base. This program will run from October 28, 2024, to November 11, 2024, at 1pm EST. The reward amount for this program is 20,000 USDC for each market to be split in a 75:25 ratio for the borrow and supply sides respectively.
> 20K usdc each to cbbtc-usdc and wsteth-usdc markets on base (fix linting issue)

- src/market-programs.ts
- src/vault-programs.ts
After the previous Universal's [uSOL campaign](https://github.com/morpho-org/morpho-blue-reward-programs/pull/59) we have decided to do another campaign to incentivize Universal's USDC Vault as well as uSOL and the newly launched uSUI market. The distribution will be as follows:
- 13.04 uSOL
- 50% will go towards borrowing on uSOL/USDC market.
- 50% will go towards Universal's USDC Vault.
- 1,051.94 uSUI
- 50% will go towards borrowing on uSUI/USDC market.
- 50% will go towards Universal's USDC Vault.
- [uSOL](https://basescan.org/tx/0x378bc5b9e3a76ee6dfea520c610547b12f6a5c80cb1dc4127329414df1852774)
- [uSUI](https://basescan.org/tx/0x899480d44c2a03b491041997262ad0437067027b223450c8cf96e979858a0434)
> Add uSUI and uSOL rewards for Universal Markets and Vault

- src/market-programs.ts
- src/vault-programs.ts
After the previous Universal's [uSOL campaign](https://github.com/morpho-org/morpho-blue-reward-programs/pull/59) we have decided to do another campaign to incentivize Universal's USDC Vault as well as uSOL and the newly launched uSUI market. The distribution will be as follows:
- 13.04 uSOL
- 50% will go towards borrowing on uSOL/USDC market.
- 50% will go towards Universal's USDC Vault.
- 1,051.94 uSUI
- 50% will go towards borrowing on uSUI/USDC market.
- 50% will go towards Universal's USDC Vault.
- [uSOL](https://basescan.org/tx/0x378bc5b9e3a76ee6dfea520c610547b12f6a5c80cb1dc4127329414df1852774)
- [uSUI](https://basescan.org/tx/0x899480d44c2a03b491041997262ad0437067027b223450c8cf96e979858a0434)
> Add uSUI and uSOL rewards for Universal Markets and Vault (#70)

- src/market-programs.ts
Add a new market reward programs for the cbBTC/USDC on Base. This program will run from Nov 6, 2024, to December 6, 2024, 1pm EST. The reward amount for this program is 25,000 USDC to be allocated entirely to the borrow side.
> 25K to cbBTC/USDC on Base

- src/market-programs.ts
- src/vault-programs.ts
We will be incentivizing Universal's USDC Vault as well as uSOL and uSUI markets. The distribution will be as follows:
- 14.09 uSOL towards the uSOL market.
- 887.97 uSUI towards the uSUI market.
- 1939.79 USDC towards the USDC market.
- [uSOL](https://basescan.org/tx/0x7597253df2ba49d4ac937551d4fbf1f0b2339265f54f1b92cda8c6b86360b854)
- [uSUI](https://basescan.org/tx/0x9b4d7e986293e6df47a6aea29ed749fb7fa7e4ff0b537b1fc9311bd73628fdb5)
- [USDC](https://basescan.org/tx/0x8d1b6b5d2d534c1ad2a0d7f5a6b7e92e555074eb1a991b1300475053ca0bc0e9)
> Universal rewards

- src/vault-programs.ts
> new pendle wbtc reward program

- src/market-programs.ts
sUSDS on base week 2 program in coordination with Sky and Theo. Sky send us payment on Monday each week and we relay to the URD.
Target is to rewards 25k USDS per week on cbBTC/sUSDS and wstETH/sUSDS supply (50-50 split).
> sUSDS on base week 2 program

- src/market-programs.ts
Add 2 new market reward programs for the cbBTC/EURC and cbETH/EURC markets on Base. This program will run from April 14, 2025, to April 28, 2025, 1pm EST. The reward amount for this program is 2K EURC for cbBTC/EURC and 1K EURC for cbETH/EURC to be allocated entirely to the borrow side.
> Incentivizing 2 new EURC markets on Base

- src/market-programs.ts
Add 2 new market reward programs for the cbBTC/EURC and cbETH/EURC markets on Base. This program will run from April 28, 2025, to May 12, 2025, 1pm EST. The reward amount for this program is 5K EURC for cbBTC/EURC and 2K EURC for cbETH/EURC to be allocated entirely to the borrow side.
> Continuing incentives on 2 EURC markets on Base
