morpho-org/morpho-blue-reward-programs

- src/vault-programs.ts
47,777 CRV over 1 month
start: 1720544708n, // Tue Jul 09 2024 17:05:08 GMT+0000
end: 1723223108n, // Fri Aug 09 2024 17:05:08 GMT+0000
> feat: add crv incentives vault program

- README.md
- package.json
> chore: update readme with warning

- src/market-programs.ts
> feat(reserve-rights): Reserve rewards bsdETH/ETH market

- src/market-programs.ts
> ovn new rewards distribution

- src/market-programs.ts
- src/vault-programs.ts
Reserve rewards on eUSD vaults on mainnet and Base
> feat(reserve-rigths): Reserve rewards eUSD vaults + markets

- src/market-programs.ts
> new ovn rewards distribution

- .github/PULL_REQUEST_TEMPLATE.md
Update the pull request template to make the merge conditions more clear.
New template:
> chore: update pull_request_template

- src/vault-programs.ts
30,450 CRV over 2 weeks
start: 1723223108n, // Fri Aug 09 2024 17:05:08 GMT+0000
end: 1724432708n, // Fri Aug 23 2024 17:05:08 GMT+0000
> feat: crv incentives for crvUSD vault epoch 2

- src/vault-programs.ts
Adds pythETH and pythUSDC rewards programs for month of August 2024
> Add pythETH and pythUSDC rewards programs

- jest.config.ts
- package.json
- src/airdrop-programs.ts
- src/index.ts
- yarn.lock
Airdrop programs are a new type of program where an incentivizer airdrops a certain amount of tokens to Morpho users. By utilizing these airdrop programs, users will be able to see and claim airdropped rewards on the Morpho UI.
> feat: add airdrop programs

- package.json
- src/airdrop-programs.ts
- src/index.ts
- yarn.lock
> chore: rename ipfsHash to cid

- src/vault-programs.ts
18,270 CRV over 2 weeks
start: 1724432708n, // Fri Aug 23 2024 17:05:08 GMT+0000
end: 1725642308n, // Fri Sep 06 2024 17:05:08 GMT+0000
> feat: crv incentives for crvUSD vault epoch 3

- src/market-programs.ts
> feat: add dinero incentives markets program

- src/market-programs.ts
- src/vault-programs.ts
> Reserve incentives in eUSD vaults and markets

- src/market-programs.ts
60'000 CFG over 60 days 
start: 1724749200n, // Tuesday, August 27, 2024 9:00:00 AM
end: 1729933200n, // Saturday, October 26, 2024 9:00:00 AM
> feat: cfg incentives for ltf/verusdc market

- src/vault-programs.ts
LlamaRisk crvUSD Vault (Epoch 4) - 14,600 CRV over 2 weeks
- start: 1725642308n, // Fri Sep 06 2024 17:05:08 GMT+0000
- end: 1726851908n, // Fri Sep 20 2024 17:05:08 GMT+0000
> feat: crv incentives for crvUSD vault epoch 4

- src/airdrop-programs.ts
https://morpho.mirror.xyz/jt9uXS6hPJZiu1rcinLRqnoCNJQX37Kh_3hGgz8ScNw
> feat(safe-pass): add SAFE Pass rewards

- src/vault-programs.ts
LlamaRisk crvUSD Vault (Epoch 5) - 29,000 CRV over 4 weeks
- start: 1726851908n, // Fri Sep 20 2024 17:05:08 GMT+0000
- end: 1729271108n, // Fri Oct 18 2024 17:05:08 GMT+0000
> feat: crv incentives for crvUSD vault epoch 5

- src/market-programs.ts
PR Update: https://github.com/morpho-org/morpho-blue-reward-programs/pull/36
> feat(market-rewards): Pyth borrow market rewards

- src/market-programs.ts
- src/vault-programs.ts
> Reserve rewards on eUSD vaults and markets

- src/market-programs.ts
> Add rsETH/WETH incentives 1/10/2024 - 14/10/2024

- src/market-programs.ts
Co-authored-by: Merlin Egalite <44097430+MerlinEgalite@users.noreply.github.com>## Context
tx: https://etherscan.io/tx/0x10b605ea4214371ae83bf613e2054cb3365f2c23dcf00f52400c6bb64c2df920
> Add cbBTC/USDC 10K market reward program on Mainnet

- src/market-programs.ts
> updating the cbBTC market

- src/market-programs.ts
> fix: update start of the program for cbBTC incentives

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Highlight PR requirements to make it clearer and more visible to programs' creators.
> feat(README):highlight requirements

- src/market-programs.ts
9.5 PAXG tokens are sent into the tx.
Split in:
- 3.15 for the first month
- 6.35 for the second month
> feat(PAXG): adding the 2 PAXG market programs on the USDC/PAXG market programs on mainnet

- src/market-programs.ts
- src/vault-programs.ts
Kindly requesting to move forward the incentives campaign dates so it starts tomorrow at 3pm GMT time.
> Move uSOL incentive campaign dates forward

- src/market-programs.ts
> Add rsETH/WETH incentives 15/10/2024 - 28/10/2024

- src/market-programs.ts
Fix linting: https://github.com/morpho-org/morpho-blue-reward-programs/pull/58
> fix: lint rseth weth

- src/vault-programs.ts
LlamaRisk crvUSD Vault (Epoch 6) - 7,500 CRV over 2 weeks
- start: 1729271108n, // Fri Oct 18 2024 17:05:08 GMT+0000
- end: 1730480708n, // Fri Nov 01 2024 17:05:08 GMT+0000
> feat: crv incentives for crvUSD vault epoch 6

- src/market-programs.ts
> wrsETH/WETH 3000 USDC on Base 18/10/2024 to 10/31/2024 00:00

- src/market-programs.ts
Signed-off-by: HedgedAdi2024 <aditya.deorukhkar1904@gmail.com>## Context
> feat(kelp): wrsETH/WETH 3000 USDC on Base 18/10/2024 to 10/31/2024

- src/market-programs.ts
- src/vault-programs.ts
> eUSD incentives in Gauntlet and Re7 WETH vaults on Base

- src/market-programs.ts
> rsETH/WETH Ethereum incentives - 10/31/2024 - 11/14/2024

- src/vault-programs.ts
LlamaRisk crvUSD Vault (Epoch 7) - 15,000 CRV over 4 weeks
- start: 1730480708n, // Fri Nov 01 2024 17:05:08 GMT+0000
- end: 1732899908n, // Fri Nov 29 2024 17:05:08 GMT+0000
](https://etherscan.io/tx/0x1f19f1f8d3694b95b3ac7999b9919212841f72032bee6b4eaf7822a720612cad)
> feat: crv incentives for crvUSD vault epoch 7

- README.md
Improve context in the README for PR verification process
> chore: add README pr verification process

- src/market-programs.ts
> wrsETH/WETH Incentives - 6th Nov - 20th Nov 2024

- src/vault-programs.ts
Pendle is giving an incentive of 1K pendle a week during 2 weeks on the pendle WBTC vault.
- [X ] Ensure there is at least one week between the PR submission and the start of the Program(s). (but team told us it will be ok)
- [ V] Send funds to the URD; the PR will only be merged after the funds have been received.
- [ V] Transaction link(s) for the funds transfer(s) to URD(s): [https://etherscan.io/tx/0x63926eca8d4ffa8c5df60d6564dca3ba2676fb147e809c135a2e4cfb92a53715]
> adding mev capital pendle rewards for pendle WBTC vault

- src/market-programs.ts
- src/vault-programs.ts
> Reserve incentives in eUSD vaults and Re7 and Gauntlet WETH vaults

- src/market-programs.ts
> rsETH/WETH incentives 21st Nov - 5th Dec 2024

- src/vault-programs.ts
- LlamaRisk crvUSD Vault (Epoch 8) - 13_514 CRV over 6 weeks
- start: 1732899908n, // Fri Nov 01 2024 17:05:08 GMT+0000
- end: 1736528708n, // Fri Jan 10 2025 17:05:08 GMT+0000
> feat: LlamaRisk crvUSD Vault (Epoch 8)

- src/vault-programs.ts
> pendle reward second step

- src/market-programs.ts
> Incentives for rsETH, agETH and wrsETH - 4th Dec - 18th Dec

- src/market-programs.ts
> feat: new cfg rewards for LTF/verUSDC market

- src/vault-programs.ts
> feat: ionic USDC

- src/vault-programs.ts
> feat: ionic WETH

- src/vault-programs.ts
~~- [] Ensure there is at least one week between the PR submission and the start of the Program(s).~~
> feat(moonwell):vault-programs

- src/market-programs.ts
- src/vault-programs.ts
> Reserve Incentives Base and Mainnet

- src/market-programs.ts
- src/vault-programs.ts
Fix conflicts of this PR: https://github.com/morpho-org/morpho-blue-reward-programs/pull/92
> fix(conflicts): Reserve Incentives Base and Mainnet 

- src/vault-programs.ts
> feat: add new programs

- src/airdrop-programs.ts
> program: PAXG rewards recover

- src/market-programs.ts
- src/vault-programs.ts
We will be incentivizing Universal's USDC Vault as well as uSOL and uSUI markets. The distribution will be as follows:
- 13.07 uSOL:
- 9.8 uSOL for borrowing on the uSOL market
- 3.27 uSOL for the Universal USDC Vault
- 476.06 uSUI:
- 119.01 uSUI for borrowing on the uSUI market
- 357.05 uSUI for the Universal USDC Vault
- 272.49 uAPT:
- 68.12 uAPT for borrowing on the uAPT market
- 204.37 uAPT for the Universal USDC Vault
- 2000 USDC towards the Universal USDC Vault
- [uSOL, uSUI, uAPT and USDC transfer](https://basescan.org/tx/0x86345505dfa3b74c41bec168c6b08f18cbf311e2a4f7828586254c066a56cc6d)
**Important**: If the delay between the PR creation and the start of the Program(s) is less than one week, or if we do not see any funds sent to the URD, the PR will not be merged, and the …
> Universal vault and market rewards

- src/market-programs.ts
- src/vault-programs.ts
> Reserve Incentives in eUSD vaults

- src/vault-programs.ts
> feat: Seamless USDC vault on Base

- src/vault-programs.ts
> feat(moonwell):programs update

- src/vault-programs.ts
> feat: ionic vaults

- src/vault-programs.ts
> feat: Seamless vaults reward updates

- src/vault-programs.ts
> Seamless ETH Vault Rewards

- src/vault-programs.ts
> feat: LlamaRisk crvUSD Vault (Epoch 9)

- src/market-programs.ts
- src/vault-programs.ts
> Reserve Incentives eUSD Vaults

- src/airdrop-programs.ts
https://snapshot.box/#/s:morpho.eth/proposal/0x2b1919fac32c16c146de220ee515dadf97b03da6df04f5e8f92f00afd5637006
> chore: spark Morpho rewards

- src/market-programs.ts
- src/vault-programs.ts
We will be incentivizing Universal's USDC Vault as well as uSOL, uSUI and uXRP markets. The distribution will be as follows:
- uSOL/USDC 6 uSOL on uSOL market on Base 3/17/2025 - 04/21/2025 2pm GMT
- uSUI/USDC 310 uSUI on uSUI market on Base 3/17/2025 - 04/21/2025 2pm GMT
- uXRP/USDC 379 uXRP on uXRP market on Base 03/03/2025 - 03/31/2025 2pm GMT
- Re7 Universal USDC Vault - 5000 USDC 03/03/2025 - 03/31/2025 2pm GMT
> New Universal incentives

- src/market-programs.ts
sUSDS on base week 1 program in coordination with Sky and Theo. Sky send us payment on Monday each week an we relay to the URD..
Target is to rewards 25k USDS per week on cbBTC/sUSDS and wstETH/sUSDS supply (50-50 split).
- [Almost] Ensure there is at least one week between the PR submission and the start of the Program(s).
> sUSDS on base week 1 program

- src/market-programs.ts
sUSDS on base week 1 program in coordination with Sky and Theo. Sky send us payment on Monday each week an we relay to the URD..
Target is to rewards 25k USDS per week on cbBTC/sUSDS and wstETH/sUSDS supply (50-50 split).
- [Almost] Ensure there is at least one week between the PR submission and the start of the Program(s).
> sUSDS on base week 1 program 

- src/market-programs.ts
Continuation of the previous campaign
> sUSDS on base week 3 program

- src/market-programs.ts
Fix https://github.com/morpho-org/morpho-blue-reward-programs/pull/119/
> add ynethx rewards (#119)

- src/market-programs.ts
- src/vault-programs.ts
> adding Maple incentives for underlying market

- src/vault-programs.ts
> feat: Seamless Vault rewards update

- src/vault-programs.ts
We will be incentivizing Universal's USDC Vault. The distribution will be as follows:
Re7 Universal USDC Vault - 5000 USDC 04/04/2025 - 04/25/2025 1pm GMT
> New Universal Vault USDC Incentives

- src/vault-programs.ts
> feat: update SEAM rewards

- src/market-programs.ts
- ✅ Ensure there is at least one week between the PR submission and the start of the Program(s).
- ✅ Send funds to the URD; the PR will only be merged after the funds have been received.
- ✅ Transaction link(s) for the funds transfer(s) to URD(s): https://basescan.org/tx/0x679b3a15b74a213cb5dabb843b44a58bb383d9faf3500302d69217c572af098c
> feat: Add wBLT/USDC market program for BMX incentives

- src/market-programs.ts
> feat: Add SYRUP incentives

- src/market-programs.ts
- src/vault-programs.ts
> Reserve eUSD vault incentives 

- src/vault-programs.ts
We will be incentivizing Universal's USDC Vault. The distribution will be as follows:
Re7 Universal USDC Vault - 5000 USDC 04/25/2025 - 05/25/2025 3pm GMT
- [x ] Send funds to the URD; the PR will only be merged after the funds have been received.
> New Universal Vault USDC Incentives 

- src/market-programs.ts
> feat: Add fxSAVE/USDC program

- src/vault-programs.ts
> chore: update kiln dates

- src/vault-programs.ts
> chore: update kiln bootstrap

- src/airdrop-programs.ts
Spark rewards following this [forum post](https://forum.morpho.org/t/mip-90-spark-usdc-deposit-rewards/1394)
> chore: spark base rewards

- src/vault-programs.ts
> feat/moonwell-flagship-vaults (#147)
